.github/workflows/dockerhub-ci-data-anonymization.yaml
data-anonymization/Dockerfile
data-anonymization/Makefile
data-anonymization/R/anonymize_household_form.R
data-anonymization/R/utils.R
data-anonymization/data-anonymization.Rproj
data-anonymization/renv.lock

Testing data anonymization into bk pipeline

add data anonymization

---

data-anonymization/R/anonymize_household_form.R
data-anonymization/README.md

remove creation of mapping tables, remove new column name for encrypted ids

added documentations

---

anomaly-detection/R/data_cleaning_function.R

https://bohemiakenya.slack.com/archives/C042P3A05UP/p1674134430480759?thread_ts=1674125355.280049&cid=C042P3A05UP

add manual append data

---

anomaly-detection/R/data_cleaning_function.R

add village cleaning

---

anomaly-detection/R/data_cleaning_function.R
anomaly-detection/renv.lock

update package requirements

---

pipeline-cleaning/R/cleaning_utils.R

Context: https://bohemiakenya.slack.com/archives/C042KSRLYUA/p1691430631014919

treat person_signed_icf as pii

---

pipeline-cleaning/R/processing_utils.R

https://trello.com/b/s98kB9HF/bohemia

Update via @sefadzi changes

---

pipeline-cleaning/R/01.run_form_cleaning.R
pipeline-cleaning/R/processing_utils.R

https://trello.com/c/rle9cOuX/2060-standardize-capitalization-in-geographic-names-in-v0demography
MAKOROKOKENI -> Mako....
Nguz0 -> Nguzo
Inconsistent spacing

add village standardization

---

pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

In this version I have updated the out table to include all individuals.

Finally fixed the blank space in out table

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

A ggplot2 library was added to fix the demographic graphs (sex and age) of absences. The cluster section now also only looks at people who are out. The second cluster graph that was appearing was also removed.

added library, absence and cluster section fixed

---

pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

fixing the eos enrolment error

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd

Rmd has the Efficacy V2 information ready, edited targets section to show how many HH visited

edited efficacy Rmd

---

pipeline-reporting/R/ento/ento_monitoring_reports.Rmd
pipeline-reporting/R/safety-efficacy/se_and_pfu.Rmd

add reporting fixes for ento and se & pfu

---

pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

now can see the specific reasons for eos, can double check that the out and refusal individuals were from previous visits.

Fixed safety

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

the first commit was wrong but has been corrected.

added a label for eos visit type

---

pipeline-reporting/R/safety-efficacy/pfu_status_and_reason.Rmd

adding visit_type causes an error so this can only uncommented once data collection has begun

added pfu info except v4 visit_type

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd

Efficacy V5 added and changed the format of the online version

Nika forgot to push Eff V5 additions

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/pfu_status_and_reason.Rmd

Also put a description of the extids that should not be in the efficacy preselection list because of dob changes that caused children to be aged out

Add efficacy preselection data

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/pfu_status_and_reason.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

- added the assignment to safety, efficacy, and pfu
- some forgotton commits that I did not push from a while ago (please check)
- also because of poor connection I did not knit this document first

added info to safety, efficacy, and pfu

---

pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/pfu_status_and_reason.Rmd
pipeline-reporting/R/safety-efficacy/pk.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

- added an efficacy flowchart (Aryton please review)
- Efficacy and safety trial profile edits requested by Paula
- started the pk script to be able to make the pk flowchart

airplane edits

---

.gitignore
pipeline-reporting/R/safety-efficacy/efficacy_status_and_reason_for_efficacy_status.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

Efficacy:
- absences and the number of people who completed efficacy have been added to the flowcharts
- the wording for efficacy on the flowcharts has been edited
- the code has been edited to properly reflect the information on the flowchart schema (dessicant color and rdt control window information for invalid tests)
Safety:
- Added the absences to safety
- Attempted to update the Safety totals tables to incorporate the correction of absences vs. other categories due to the order of counting. Need to check and see if this worked

safety and efficacy edits

---

pipeline-reporting/R/safety-efficacy/pfu_status_and_reason.Rmd
pipeline-reporting/R/safety-efficacy/safety_status_and_reason_for_safety_status.Rmd

https://bohemiakenya.slack.com/archives/D057A2K7TT7/p1722617314441659

Nika'changes
